spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phone_book?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: golovach
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create